<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\cleaner-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\cleaner-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Cleaner.Tests\**" />
    <Compile Remove="publish\**" />
    <EmbeddedResource Remove="Cleaner.Tests\**" />
    <EmbeddedResource Remove="publish\**" />
    <None Remove="Cleaner.Tests\**" />
    <None Remove="publish\**" />
    <Page Remove="Cleaner.Tests\**" />
    <Page Remove="publish\**" />
  </ItemGroup>

</Project>
